on:
  push:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - run: echo $SHELL
        shell: bash
      - run: echo $SHELL
        shell: wslbash
      - run: echo $SHELL
      - run: echo %SHELL%
        shell: cmd
