on:
  push:

jobs:
  test:
    runs-on: windows-latest
    defaults:
      run:
        shell: wsl-bash {0}
    steps:
      - uses: Vampire/setup-wsl@v1
      - run: ls -la
      - uses: actions/checkout@v2
      - run: ls -la
      - uses: actions/cache@v2
        id: cache
        with:
          path: cache
          key: cache-v2
      - run: echo "cache-hit=${{ steps.cache.outputs.cache-hit }}"
      - run: |
          mkdir cache
          cd cache
          touch a.txt
          touch b.txt
        if: steps.cache.outputs.cache-hit != 'true'
      - run: ls -la
      - run: ls -la cache
