on:
  push:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - run: echo $SHELL
        shell: bash
      - run: echo $SHELL
        shell: C:\Windows\System32\bash.exe
      - run: make -v
        shell: bash
      - run: make -v
